title = "edouard.paris"
baseURL = "https://edouard.paris"
theme = ["phrck"]
DefaultContentLanguage = "en"
pluralizeListTitles = false
enableGitInfo = true

[markup]
[markup.tableOfContents]
endLevel = 3
startLevel = 1

[taxonomies]
tag = "tags"
topic = "topics"

[permalinks]
topics = "/:slug"

[frontmatter]
date = ["date", "lastmod"]
lastmod = [":git"]

[blackfriday]
angledQuotes = false

[outputFormats.Txt]
name = "txt"
baseName = "index"
mediaType = "text/plain"
isPlainText = true

[outputs]
 home = ["HTML", "txt"]
 page = ["HTML", "txt"]
 section = ["HTML", "txt"]

[languages.en]
redirect = "Read this page in your terminal with the command:"
copyright = "2020 EdouardParis."
description = "Edouard Paris personal website"

[[languages.en.menu.lang]]
url = "/fr"
name = "fr"
weight = 0
pre= "/"

[[languages.en.menu.lang]]
url = "/"
name = "en"
weight = 0


[[languages.en.menu.main]]
url = "/readings"
name = "readings"
weight = 0

[[languages.en.menu.main]]
name = "writing"
identifier = "writing"
weight = 2

[languages.fr]
redirect = "Lisez cette page dans un terminal avec la commande:"
copyright = "2020 EdouardParis."
description = "Site web personnel de Edouard Paris"

[[languages.fr.menu.lang]]
url = "/fr"
name = "fr"
weight = 0
pre = "/"

[[languages.fr.menu.lang]]
url = "/"
name = "en"
weight = 0

[[languages.fr.menu.main]]
url = "/fr/lecture"
name = "lecture"
weight = 0

[[languages.fr.blackfriday]]
angledQuotes = true
