title = "edouard.paris"
baseURL = "https://edouard.paris"
theme = "phrck"
DefaultContentLanguage = "en"
pluralizeListTitles = false

[blackfriday]
angledQuotes = false

[languages.en]
copyright = "2018 EdouardParis."

[[languages.en.menu.lang]]
url = "/fr"
name = "fr"
weight = 0
pre= "/"

[[languages.en.menu.lang]]
url = "/"
name = "en"
weight = 0


[[languages.en.menu.main]]
url = "/reading"
name = "reading"
identifier = "reading"
weight = 1

[[languages.en.menu.main]]
url = "/reading/books"
name = "books"
parent = "reading"
weight = 0

[[languages.en.menu.main]]
name = "about"
identifier = "about"
weight = 0


[[languages.en.menu.main]]
url = "/contact"
name = "contact"
parent = "about"
weight = 0


[languages.fr]
copyright = "2018 EdouardParis."

[[languages.fr.menu.lang]]
url = "/fr"
name = "fr"
weight = 0
pre = "/"

[[languages.fr.menu.lang]]
url = "/"
name = "en"
weight = 0

[[languages.fr.menu.main]]
url = "/fr/reading"
name = "lecture"
identifier = "lecture"
weight = 0

[[languages.fr.menu.main]]
url = "/fr/reading/books"
name = "livres"
parent = "lecture"
weight = 0

[[languages.fr.menu.main]]
name = "Ã  propos"
identifier = "a-propos"
weight = 0

[[languages.fr.menu.main]]
url = "/fr/contact"
name = "contact"
parent = "a-propos"
weight = 0

[[languages.fr.blackfriday]]
angledQuotes = true
